### ISSUE TITLE
Back-end: Define app dependencies, and install them for use.

### ISSUE THREAD

**Issue by jallan07** [jallan07/gitjobs-application-tracker#5]
We need to define the different app dependencies (express, template engine(?), Sequelize, MySQL, etc.) and run npm install on all of them so we can use them as we build out the app.

**Comment by markdcross** [comment]
First round of dependencies installed (body-parser, express, mysql2, passport, sequelize) and sequelize CLI initialized

**Comment by markdcross** [comment]
Handlebars added, along with linkedin-oauth and express-session
